version: '3.1'

services:
  odoo:
    build: ./
    container_name: odoo_hiscox
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./hiscox:/mnt/extra-addons/hiscox
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo_pg_data:/var/lib/postgresql/data

volumes:
  odoo_pg_data:
